### ISSUE TITLE
FactoryInterface type with traits

### ISSUE THREAD

**Issue by subvertallchris** [Quramy/prisma-fabbrica#245]
Hello again! Can you share some advice on using the `XyzFactoryInterface` so that it has an awareness of traits? The type takes a generic, `TOptions`, but it looks like it wants something elaborate and I can't pin it down and don't see examples in the tests.

Thank you!

**Comment by Quramy** [comment]
`XyzFactoryInterface` is used to avoid TS circular reference error.

https://github.com/Quramy/prisma-fabbrica?tab=readme-ov-file#suppress-ts-circular-dependencies-error

And  the type parameter `TOptions` is defined to infer concrete traits keys from argument `defineXyzFactory` .

**Comment by Quramy** [comment]
I wrote docs about type parameters of Factory Interface (#338)
