### ISSUE TITLE
TypeScript error when exporting defined factories: symbol factoryFor cannot be named

### ISSUE THREAD

**Issue by jenrzzz** [Quramy/prisma-fabbrica#281]
After the change to make `factoryFor` a private symbol, exporting a generated factory results in a type error: 

`Exported variable 'FooFactory' has or is using name 'factoryFor' from external module "test/factories/fabbrica/index" but cannot be named.`

The error occurs on this line:
 
```typescript
export const FooFactory = defineFooFactory();
```

**Comment by Quramy** [comment]
@jenrzzz 
Thanks for reporting. I fixed and released as v2.1.1

**Comment by jenrzzz** [comment]
@Quramy Woohoo! Thanks so much for the support and for creating all these things that make using Prisma tolerable for a spoiled former Rails developer <3
