### ISSUE TITLE
Ignores the `@db.VarChar()` attribute length constraint.

### ISSUE THREAD

**Issue by yamada-wacul** [Quramy/prisma-fabbrica#328]
**Describe the bug**

Even the field having the atttribute like `@db.VarChar(10)` that constrains the length of the value, fabbrica may generate values too long for the contraint.

**To Reproduce**

*I will prepare it at later...*

**Expected behavior**
Cut the value generated with the limit.

**Your Schema**

```
model Sample {
  name String @db.VarChar(10)
}
```

**Environment (please complete the following information):**

- Database kind: PostgreSQL
- Node.js version: v20.9.0
- `@prisma/client` version: 5.15.0
- TypeScript version: 5.4.5

**Additional context**

Please put gist URL including generated .js and .d.ts if you can :pray:

*i will prepaere it at leter...*

**Comment by Quramy** [comment]
For now, prisma-fabbrica's scalar auto filling function does not refer `@db.****` annotation.

But the scalar auto filling function can be customized in user-land.
https://github.com/Quramy/prisma-fabbrica?tab=readme-ov-file#custom-scalar-field-generation

For example, the following function always generates a string of 10 characters or less:

```ts
import { registerScalarFieldValueGenerator } from "./__generated__/fabbrica";

registerScalarFieldValueGenerator({
  String: ({ isId, isUnique, seq }) => {
    if (isId || isUnique) {
      return `${seq}`.padStart(10, "0");
    }
    return fieldName.slice(0, 10);
  },
});
```

**Comment by yamada-wacul** [comment]
@Quramy thanks, i see.
