### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by Quramy** [Quramy/prisma-fabbrica#5]
### Investigating 
- [x] #42

### ToDos before publish first version

- [x] Auto generate required scalar fields
- [x] #10
- [x] #7
- [x] #8
- [x] #6
- [x] #14
- [x] #15
- [x] #28

### After first version published

- [x] #43
- [x] #34
- [x] #35
- [x] #36
- [x] #48
- [x] #70
- [x] #27

**Comment by youssefm** [comment]
This project is amazing. Thanks for putting this out there @Quramy.
