### ISSUE TITLE
Unknown scalar type "Null" for ... .

### ISSUE THREAD

**Issue by tkow** [Quramy/prisma-fabbrica#50]
**Describe the bug**
If defining nullable column in schema.prisma, fabrrica generator fails to transpile.

**To Reproduce**

Rewrite example-prj's schema.prisma in this repository as like followed by example.

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}

generator fabbrica {
  provider = "prisma-fabbrica"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id    String @id
  name  String?
  posts Post[]
}

model Post {
  id       String @id
  title    String
  author   User   @relation(fields: [authorId], references: [id])
  authorId String
}
```

and `npx prisma migrate dev`

**Expected behavior**

Generate fabbrica codes.

**Your Schema**

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}

generator fabbrica {
  provider = "prisma-fabbrica"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id    String @id
  name  String?
  posts Post[]
}

model Post {
  id       String @id
  title    String
  author   User   @relation(fields: [authorId], references: [id])
  authorId String
}
```

**Environment (please complete the following information):**

- Database kind [PostgreSQL, sqlite]
- Node.js version [v16.15.0]
- `@prisma/client` version [4.6.1]
- TypeScript version [e.g. 4.9.3]

**Additional context**

**Comment by Quramy** [comment]
Oops, I'm sorry. I'll fix this and thanks for your reporting!
