### ISSUE TITLE
NODE_ENV="development" stops generating codes if typescript's tests not passed, and Node TypeLiteral did not pass test 'isEntityName'  always fails

### ISSUE THREAD

**Issue by tkow** [Quramy/prisma-fabbrica#62]
**Describe the bug**

If specifying `NODE_ENV="development"` and run prisma-fabbrica generators then type tests aren't passed, it stops generating code though it continues with other values.

Now, maybe due to `Node TypeLiteral did not pass test 'isEntityName'` warning,  anytime it stops now when setting `NODE_ENV="development"` .

<img width="964" alt="スクリーンショット 2022-11-30 10 07 49" src="https://user-images.githubusercontent.com/7004725/204684479-e67fbf98-53c7-47ac-8238-7feaa9fa9f10.png">

**To Reproduce**
Set env variables NODE_ENV="development" and run `npm run migrate:test:ci` in example-prj directory.

**Expected behavior**

There are two choices.

1. If not allowing warning, fix `Node TypeLiteral did not pass test 'isEntityName' `
2. If allowing warning, skip this exception and continue to generate codes.

**Your Schema**

Maybe any schema I tested if warning occurs.

**Environment (please complete the following information):**

- Database kind [any]
- Node.js version [any?]
- `@prisma/client` version [4.6.1]
- TypeScript version [4.9.3]

**Additional context**

**Comment by Quramy** [comment]
Thanks for your reporting!

I've heard the warning, but I want to choice this option.

> 1. If not allowing warning, fix Node TypeLiteral did not pass test 'isEntityName'

I'll investigate and attempt to fix this.

**Comment by Quramy** [comment]
I fixed this via #63 and published as v0.2.4 .
