### ISSUE TITLE
Enums not imported

### ISSUE THREAD

**Issue by leandrit1** [Quramy/prisma-fabbrica#88]
**Describe the bug**
The generated `index.ts` doesn't import all `enums` from `schema.prisma`. In my case, it contains most but a few, and it looks like only `enums` that are set on just `optional` fields are not imported, despite being assigned correctly, which causes the app to break due to missing imports.
i.e Here the enum is set, but it's not imported
<img width="503" alt="image" src="https://user-images.githubusercontent.com/24826344/213106906-afa412c5-bc24-47c7-98a0-8f299877e812.png">

**To Reproduce**
1. Create an enum type in `schema.prisma`, and set it to an `optional` field. *Don't use the same `enum` elsewhere (especially in a required field).
2. generate Prisma models
3. Visit the generated module, and most likely you will see that enum is not imported

**Expected behavior**
The `enums` should be imported

**Comment by Quramy** [comment]
@leandrit1 

Thanks for your reporting this issue. I fixed this and published as v1.0.1

**Comment by leandrit1** [comment]
Thanks man. Awesome package!
