### ISSUE TITLE
Create models without persisting

### ISSUE THREAD

**Issue by ssukienn** [Quramy/prisma-fabbrica#90]
**Feature request**

Would that be possible to conditionally resign from persistence and simulate best-effort models' response from a `create` related API? 
In another words could we derive `Account` type from `AccountCreateInput` without persisting to Prisma

 Really nice library!

**Comment by Quramy** [comment]
Hi @ssukienn 

I think it's difficult.
For example, if the `Account` model is defined as the following, we should simulate the `autoincrement()` function, which is provided by not Prisma client but RDB.

```graphql
model Account {
  id  Int  @id @default(autoincrement())
}
```

Of course, we know  `autoincrement` can be simulated using `++count` . 

However, 

- It's touch to simulate all functions available in schema
- I want to keep prisma-fabbrica  responsible to only build input data for `create` method.
