### ISSUE TITLE
Use prisma-fabbrica in real world application

### ISSUE THREAD

**Issue by leonard-henriquez** [Quramy/prisma-fabbrica#94]
Hi @Quramy ,
I've just discovered this library that looks awesome 😍  !! (please keep working on it ;) )
It looks like you have just release the first stable version but I am a bit worried about using it on a real world application.

What are your plans for this project ? 
Do you plan on maintaining it on the long run ?
Do you plan on maintaining this project alone ? Do you plan on involving maintainers (people or companies) ?
Do you know how many companies use it in real world project ?
Do you plan on respecting SemVer (particularly respecting the major version update when introducing breaking changes) ?
Have you tested it with other users before releasing the first stable version ?

Sorry for all those annoying question, but I'm pretty sure that if you plan maintaining this project on the long run it will become a few hundreds/thousands stars project !

In any case, thank you for your work on this project 🙂

**Comment by Quramy** [comment]
Hi @leonard-henriquez 

> Do you plan on maintaining it on the long run

Yes.  I don't think "how long", but I maintain some npm packages( e.g. https://github.com/Quramy/ts-graphql-plugin, and others) in several years. 

> Do you plan on maintaining this project alone

Yes (for now) . But I'm welcome to contributing by other developers.

> Do you know how many companies use it in real world project 

I don't know. Of course I use this at my work. However this project is so young. I think few companies use this for now.
Please send me feedback if you try this 😄 

> Do you plan on respecting SemVer (particularly respecting the major version update when introducing breaking changes)

Absolutely yes. I don't add breaking changes for v1.x.x 

> Have you tested it with other users before releasing the first stable version ?

Yes. I created this package to developer experience for integration testing ( Related blog post: https://quramy.medium.com/test-your-prisma-app-part-2-prisma-fabbrica-test-data-factory-utility-89f8f4c36302 ).
Test codes in my product (it works in real world) had be  written not using database factory utils. I replaced the test codes to use prisma-fabbrica not adding change assertion. Some bugs were found during the replace and I fixed them before release v1.0.0 .

**Comment by leonard-henriquez** [comment]
Thank you very much for your answers !
Seems like a great project. I will be glad to try it with my company and I would be very happy to share feedbacks/contribute if we have the opportunity !

PS: I don't know if you know the gem (packages in the ruby ecosystem) [FactoryBot](https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md) but it does pretty much the same thing for the ActiveRecord ORM. It's a very mature project with a lot of really cool features. It could be a great source of inspiration if you don't already know about it!

**Comment by Quramy** [comment]
Yes, FactoryBot and RSpec Rails inspired me. So I built prisma-fabbrica and jest-prisma to make up for the lack of Prisma ecosystem 😄
