### ISSUE TITLE
Use Prisma extension instead of generator

### ISSUE THREAD

**Issue by leonard-henriquez** [Quramy/prisma-fabbrica#99]
Hi @Quramy 
I stumbled upon another factory library: https://prisma-extensions.io/.
They use Prisma extension to have a really clean API without the need to generate new files.

Here is what their API look like:
```
import { PrismaClient } from '@prisma/client';
import { factoryExtension } from '@prisma-extensions/factory';

const prisma = new PrismaClient();
const db = prisma.$extends(factoryExtension);

const UserFactory = db.user.$factory({
  firstName: 'Tom',
  lastName: 'Milewski',
})

UserFactory.attributes();

UserFactory.create();
```

Except if the generator provide really awesome features which are not possible with prisma client, I think Prisma Fabbrica should head into this direction.
I know it would introduce breaking changes and would require a v2 but I think it would be better on the long run.
First, Prisma seems to favor extensions to generator because they are more composable. Besides, generated files can slow build tasks and produce weird problems due to stale files.
What do you think ?

PS: Unfortunately the code of the library isn't released publicly yet.

**Comment by Quramy** [comment]
@leonard-henriquez 

> Prisma Fabbrica should head into this direction.

I don't think so , for now.

Let me explain why prisma-fabbrica adopts generator approach.
 
prisma-fabbrica reads models structure(e.g. which fields is PK or has unique constraints or ...) from DMMF which is structural data model from schema.prisma file . And prisma-fabbrica can generate field values or relationship models omitted at factories arguments. For example, if you omit unique field when `create`, fabbrica generates the field value without duplication.

I read https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions/model#add-a-custom-method-to-all-models-in-your-schema but I can't find how to access DMMF from extension.

**Comment by leonard-henriquez** [comment]
From what I see prisma extensions are still in "feature preview".
Would it be worth to ask in [this thread](https://github.com/prisma/prisma/issues/16500) if they could consider giving access to DMMF to prisma extensions ?
It seems like someone already [has a similar use case](https://github.com/prisma/prisma/issues/16500#issuecomment-1331535133).
